'use strict';
const assert=require('assert/strict'),http=require('http'),fs=require('fs'),path=require('path');
const browserType=require('playwright')[process.env.SW_TEST_BROWSER||'chromium'];const root=path.resolve('.'),port=Number(process.env.SW_TEST_PORT||8239);
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://test').pathname);if(!p.startsWith(root+path.sep)||!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');fs.createReadStream(p).pipe(res);});
(async()=>{await new Promise(r=>server.listen(port,'127.0.0.1',r));let browser;
 try{browser=await browserType.launch({args:process.env.SW_TEST_BROWSER==='webkit'?[]:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true});let writes=0,fail=false;const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const origin='http://127.0.0.1:'+port;await page.route('**/*',async route=>{const req=route.request();if(req.method()!=='GET')writes++;if(req.url().endsWith('/api/storage-health'))return route.fulfill({status:fail?503:200,contentType:'application/json',body:JSON.stringify({capacity_status:'WARNING',current_files:774,current_file_bytes:1681179555,repository_bytes:7039696896,checkpoint:{verified:true,wallets:423,state_version:242},backup:{independent_restore_verified:false},automatic_rollover_enabled:false})});if(req.url().endsWith('/api/wallet-admission'))return route.fulfill({contentType:'application/json',body:JSON.stringify({candidates:[{address:'rExample',transaction_count:2,total_xrp:6000000}],apply_status:'Automatic additions disabled.'})});return req.url().startsWith(origin)?route.continue():route.abort();});
  await page.goto(origin+'/storage-status.html');await page.click('#refresh');await page.waitForFunction(()=>document.getElementById('status').textContent.includes('WARNING'));assert.match(await page.locator('#metrics').textContent(),/423/);assert.match(await page.locator('#backup').textContent(),/not verified/);
  await page.click('#qualify');await page.waitForFunction(()=>document.getElementById('qualification').textContent.includes('preview only'));assert.match(await page.locator('#candidates').textContent(),/Ownership unknown/);assert.equal(writes,0);assert.deepEqual(errors,[]);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'phone layout must not overflow');fail=true;await page.click('#refresh');await page.waitForFunction(()=>document.getElementById('status').textContent.includes('could not finish'));assert.equal(await page.locator('#refresh').isDisabled(),false);
  console.log('PASS mobile storage status: truthful capacity/backup state, read-only qualification preview, error recovery, no overflow or page errors');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
